config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get 'index' => 'home#index'

  get 'services' => 'services#moving'
  get 'services/moving' => 'services#moving'
  get 'services/packing_and_reassembly' => 'services#packing_and_reassembly'
  get 'services/storage' => 'services#storage'
  get 'services/special_furnitures' => 'services#special_furnitures'

  get 'licences_and_insurances' => 'licences_and_insurances#licences_and_insurances'

  get 'quotation' => 'quotation#quotation'
  get 'tips' => 'tips#tips'
  get 'contact_us' => 'contact_us#contact_us'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController

  def contact_us
    @address = "<strong>9370 S.W. 8th Street Suite 117</strong><br>Boca Raton, FL 33428"
    @phoneNumber = "+1 561 672 4545"
    @emailAddress = "info@moveamericafl.com"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @phoneNumber = "+1 561 672 4545"
  end
end

app/controllers/licences_and_insurances_controller.rb
class LicencesAndInsurancesController < ApplicationController

  def licences_and_insurances
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @phoneNumber = "+1 561 672 4545"
  end
end

app/controllers/quotation_controller.rb
class QuotationController < ApplicationController
  def quotation
    @address = "<strong>9370 S.W. 8th Street Suite 117</strong><br>Boca Raton, FL 33428"
    @phoneNumber = "+1 561 672 4545"
    @emailAddress = "info@moveamericafl.com"
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def moving
  end

  def storage
  end

  def packing_and_reassembly
  end

  def special_furnitures
  end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  def tips
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header>
  <div id="top_line">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6">
          <span id="tag_line">Free Estimates · Best Prices · Friendly Service</span>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6">
          <ul id="top_links">
            <li><span id="phone_header"><strong><h5><a href= "tel:+1 561 672 4545">CALL US! +1 561 672 4545</a></h5></strong></span></li>
          </ul>
        </div>
      </div><!-- End row -->
    </div><!-- End container-->
  </div><!-- End top line-->

  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-3 col-xs-3">
        <div id="logo">
          <%= link_to root_path do %>
              <%= image_tag 'logo/logo.png', size: "150x35", data_retina: true %>
          <%end%>
        </div>
      </div>
      <nav class="col-md-9 col-sm-9 col-xs-9">
        <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
        <div class="main-menu">
          <div id="header_menu">
            <%= link_to root_path do %>
                <%= image_tag 'logo/logo.png', size: "150x35", data_retina: true %>
            <%end%>
          </div>
          <a href="#" class="open_close" id="close_in"><i class="icon_close"></i></a>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li class="submenu">
              <a href="javascript:void(0);" class="show-submenu">Services <i class="icon-down-open-mini"></i></a>
              <ul>
                <li><%= link_to "Moving", services_moving_path %></li>
                <li><%= link_to "Packing and Reassembly", services_packing_and_reassembly_path %></li>
                <li><%= link_to "Storage", services_storage_path %></li>
                <li><%= link_to "Special Furnitures", services_special_furnitures_path %></li>
              </ul>
            </li>
            <li><%= link_to "Licences and Insurances", licences_and_insurances_path %></li>
            <li><%= link_to "Tips", tips_path %></li>
            <li><%= link_to "Quotation", quotation_path %></li>
            <li><%= link_to "Contact Us", contact_us_path %></li>
          </ul>
        </div><!-- End main-menu -->
      </nav>
    </div>
  </div><!-- container -->
</header><!-- End Header -->

app/views/licences_and_insurances/licences_and_insurances.erb
<section id="sub_header">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8">
        <div class="main_title">
          <h1><i class="icon-folder-open"></i> Licences and Insurances</h1>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</section><!-- End section -->

<div class="container margin_60">
  <div class="row">

    <div class="col-md-9">
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="box_style_4">
            <h3>Licences</h3>
            <table class="table table-striped">
              <thead>
              <tr>
                <th>Licence</th>
                <th>Valid for</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>Licence #1</td>
                <td>Florida</td>
              </tr>
              <tr>
                <td>Licence #2</td>
                <td>USA</td>
              </tr>
              <tr>
                <td>Licence #3</td>
                <td>Fl, Ny, Ca</td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div><!-- End row -->
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="box_style_4">

            <h3>Insurances</h3>
            <table class="table table-striped">
              <thead>
              <tr>
                <th>Insurance</th>
                <th>Up to</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>Insurance #1</td>
                <td>$5,000,000.00</td>
              </tr>
              <tr>
                <td>Insurance #2</td>
                <td>$5,000,000.00</td>
              </tr>
              <tr>
                <td>Insurance #3</td>
                <td>$5,000,000.00</td>
              </tr>
              <tr>
                <td>Insurance #4</td>
                <td>$5,000,000.00</td>
              </tr>
              </tbody>
            </table>

          </div>
        </div>
      </div><!-- End row -->
    </div><!-- End col-md-9 -->

    <div class="col-md-3">
      <div class="box_style_1">
        <ul id="cat_nav">
          <li><%= link_to "Moving", services_moving_path %></li>
          <li><%= link_to "Packing and Reassembly", services_packing_and_reassembly_path %></li>
          <li><%= link_to "Storage", services_storage_path %></li>
          <li><%= link_to "Special Furnitures", services_special_furnitures_path %></li>
        </ul>
        <hr>
        <h5>Did you find what you need?</h5>
        <p class="nopadding"><%= link_to "Contact Us", contact_us_path %></p>

      </div><!-- End Box_style_1 -->

      <div class="quote_banner"><%= link_to "Need a quotation?", "quotation#index" %></div>

    </div><!-- End col-md-3 -->
  </div><!-- End row -->
</div><!-- End container -->

app/views/services/moving.html.erb
<section id="sub_header">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8">
        <div class="main_title">
          <h1><i class="icon-upload-4"></i> Moving</h1>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</section><!-- End section -->

<div class="container margin_60">
  <div class="row">

    <div class="col-md-9">
      <%= image_tag "pages/moving/moving-main.jpg", class:"img-responsive border" %>
      <h3>Moving globally</h3>
      <p>Ad qui consulatu scripserit comprehensam. Eum <strong>purto epicurei cotidieque</strong> at, ius luptatum invidunt no, vim at sint pertinacia repudiandae. Ad cum dicant laboramus delicatissimi, ex has nonumes explicari prodesset, brute tincidunt conclusionemque no has. Sit ullum latine ei. Ius id adhuc iriure torquatos. Justo prompta senserit eos cu, omnesque posidonium liberavisse pri in. Malorum fabulas elaboraret mea in, vel ut harum tacimates posidonium.</p>

      <div class="row">
        <div class="col-md-6">
          <%= image_tag "pages/moving/moving-sub-1.jpg", class:"img-responsive border" %>
          <h3>Complete transport solutions</h3>
          <p>Ad sed apeirian senserit gloriatur, eu iusto ubique impetus quo. Sea no essent cotidieque reformidans, sea an <strong>persius moderatius</strong> comprehensam, at nam tamquam alterum definiebas. Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
        </div>
        <div class="col-md-6">
          <%= image_tag "pages/moving/moving-sub-2.jpg", class:"img-responsive border" %>
          <h3>Documentation management</h3>
          <p>Ad sed apeirian senserit gloriatur, eu iusto ubique impetus quo. Sea no <strong>essent cotidieque</strong> reformidans, sea an persius moderatius comprehensam, at nam tamquam alterum definiebas. Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
        </div>
      </div><!-- End row -->

      <hr>

      <div class="row">
        <div class="col-md-6">
          <ul class="feat">
            <li>
              <%= image_tag "icons/icon_domestic_1.png", size:"50x54", data_retina:true %>
              <h4>Fast moving service</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
            <li>
              <%= image_tag "icons/icon_domestic_2.png", size:"50x56", data_retina:true %>
              <h4>Secure checklist</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
            <li>
              <%= image_tag "icons/icon_domestic_3.png", size:"50", data_retina:true %>
              <h4>Packing service</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
            <li>
              <%= image_tag "icons/icon_domestic_4.png", size:"50", data_retina:true %>
              <h4>Delicate Packing service</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
            <li>
              <%= image_tag "icons/icon_international_3.png", size:"50", data_retina:true %>
              <h4>Dedicate Help center</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
          </ul>
        </div>
        <div class="col-md-6">
          <ul class="feat">
            <li>
              <%= image_tag "icons/icon_domestic_5.png", size:"50", data_retina:true %>
              <h4>Heavy furniture</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
            <li>
              <%= image_tag "icons/icon_domestic_6.png", size:"50", data_retina:true %>
              <h4>Cargo service</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
            <li>
              <%= image_tag "icons/icon_international_1.png", size:"50", data_retina:true %>
              <h4>Container Ship</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
            <li>
              <%= image_tag "icons/icon_international_2.png", size:"50", data_retina:true %>
              <h4>Transport</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
          </ul>
        </div>
      </div><!-- End row -->

    </div><!-- End col-md-9 -->

    <div class="col-md-3">
      <div class="box_style_1">
        <ul id="cat_nav">
          <li><%= link_to "Moving", services_moving_path %></li>
          <li><%= link_to "Packing and Reassembly", services_packing_and_reassembly_path %></li>
          <li><%= link_to "Storage", services_storage_path %></li>
          <li><%= link_to "Special Furnitures", services_special_furnitures_path %></li>
        </ul>
        <hr>
        <h5>Did you find what you need?</h5>
        <p class="nopadding"><%= link_to "Contact Us", contact_us_path %></p>

      </div><!-- End Box_style_1 -->

      <div class="quote_banner">
        <%= link_to quotation_path do %>
            <i class="icon_calulator"></i> Need a Quotation?
        <%end%>
      </div>

      <div class="box_style_2">
        <h4>Removal tips</h4>
        <h5><i class="icon_toolbox_alt"></i> Preparing</h5>
        <ul>
          <li>Defrost your refrigerator in time for moving day.</li>
          <li>It’s useful to keep a notebook at hand to write down reminders.</li>
          <li>Get in touch with utility companies to verify service start dates at your new home.</li>
        </ul>
        <h5><i class="icon_tag_alt"></i> Packing and labeling</h5>
        <ul>
          <li>Label boxes on all sides so you can see what it contains in a stack without having to move everything around.</li>
          <li>Clearly mark boxes containing fragile goods.</li>
          <li>Pack a suitcase with clothes and toiletries like you’re going on a trip for a few days.</li>
        </ul>
        <p><%= link_to "Read More", tips_path %></p>
      </div>

    </div><!-- End col-md-3 -->

  </div><!-- End row -->
</div><!-- End container -->

app/views/services/packing_and_reassembly.html.erb
<section id="sub_header">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8">
        <div class="main_title">
          <h1><i class="icon_tags"></i> Reassembly and Packing</h1>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</section><!-- End section -->

<div class="container margin_60">
  <div class="row">
    <div class="col-md-9">
      <%= image_tag "pages/packing/packing-main.jpg", class:"img-responsive border" %>
      <h3>Packing service</h3>
      <p class="add_bottom_30">
        Ad qui consulatu scripserit comprehensam. Eum <strong>purto epicurei cotidieque</strong> at, ius luptatum invidunt no, vim at sint pertinacia repudiandae. Ad cum dicant laboramus delicatissimi, ex has nonumes explicari prodesset, brute tincidunt conclusionemque no has. Sit ullum latine ei. Ius id adhuc iriure torquatos. Justo prompta senserit eos cu, omnesque posidonium liberavisse pri in. Malorum fabulas elaboraret mea in, vel ut harum tacimates posidonium.
      </p>
      <h3>Reassembling Service</h3>
      <p class="add_bottom_30">
        Ad qui consulatu scripserit comprehensam. Eum <strong>purto epicurei cotidieque</strong> at, ius luptatum invidunt no, vim at sint pertinacia repudiandae. Ad cum dicant laboramus delicatissimi, ex has nonumes explicari prodesset, brute tincidunt conclusionemque no has. Sit ullum latine ei. Ius id adhuc iriure torquatos. Justo prompta senserit eos cu, omnesque posidonium liberavisse pri in. Malorum fabulas elaboraret mea in, vel ut harum tacimates posidonium.
      </p>

      <div class="box_style_3 add_bottom_15">
        <div class="row">
          <div class="col-md-4 text-center">
            <p>
              <%= image_tag "icons/reassembly_icon_1.png", size:"110x100", data_retina:true %>
            </p>
            <h4>1. Preparing</h4>
            <p>
              Lorem ipsum dolor sit amet, has eu scaevola facilisi maluisset, sea te cibo similique, tollit feugait senserit mei te.
            </p>
          </div>
          <div class="col-md-4 text-center">
            <p>
              <%= image_tag "icons/reassembly_icon_2.png", size:"74x100", data_retina:true %>
            </p>
            <h4>2. Collecting</h4>
            <p>
              Lorem ipsum dolor sit amet, has eu scaevola facilisi maluisset, sea te cibo similique, tollit feugait senserit mei te.
            </p>
          </div>
          <div class="col-md-4 text-center">
            <p>
              <%= image_tag "icons/reassembly_icon_3.png", size:"171x100", data_retina:true %>
            </p>
            <h4>3. Moving</h4>
            <p>
              Lorem ipsum dolor sit amet, has eu scaevola facilisi maluisset, sea te cibo similique, tollit feugait senserit mei te.
            </p>
          </div>
        </div><!-- End row -->
      </div>
    </div><!-- End col-md-9 -->

    <div class="col-md-3">
      <div class="box_style_1">
        <ul id="cat_nav">
          <li><%= link_to "Moving", services_moving_path %></li>
          <li><%= link_to "Packing and Reassembly", services_packing_and_reassembly_path %></li>
          <li><%= link_to "Storage", services_storage_path %></li>
          <li><%= link_to "Special Furnitures", services_special_furnitures_path %></li>
        </ul>
        <hr>
        <h5>Did you find what you need?</h5>
        <p class="nopadding"><%= link_to "Contact Us", contact_us_path %></p>

      </div><!-- End Box_style_1 -->

      <div class="quote_banner">
        <%= link_to quotation_path do %>
            <i class="icon_calulator"></i> Need a Quotation?
        <%end%>
      </div>

      <div class="box_style_2">
        <h4>Removal tips</h4>
        <h5><i class="icon_toolbox_alt"></i> Preparing</h5>
        <ul>
          <li>Defrost your refrigerator in time for moving day.</li>
          <li>It’s useful to keep a notebook at hand to write down reminders.</li>
          <li>Get in touch with utility companies to verify service start dates at your new home.</li>
        </ul>
        <h5><i class="icon_tag_alt"></i> Packing and labeling</h5>
        <ul>
          <li>Label boxes on all sides so you can see what it contains in a stack without having to move everything around.</li>
          <li>Clearly mark boxes containing fragile goods.</li>
          <li>Pack a suitcase with clothes and toiletries like you’re going on a trip for a few days.</li>
        </ul>
        <p><%= link_to "Read More", tips_path %></p>
      </div>

    </div><!-- End col-md-3 -->

  </div><!-- End row -->
</div><!-- End container -->

app/views/services/special_furnitures.html.erb
<section id="sub_header">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8">
        <div class="main_title">
          <h1><i class="icon-star"></i> Special Furnitures</h1>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</section><!-- End section -->

<div class="container margin_60">
  <div class="row">

    <div class="col-md-9">
      <%= image_tag "pages/special/special-main.jpg", class:"img-responsive border" %>
      <h3>Art and antique furnitures</h3>
      <p>Ad qui consulatu scripserit comprehensam. Eum <strong>purto epicurei cotidieque</strong> at, ius luptatum invidunt no, vim at sint pertinacia repudiandae. Ad cum dicant laboramus delicatissimi, ex has nonumes explicari prodesset, brute tincidunt conclusionemque no has. Sit ullum latine ei. Ius id adhuc iriure torquatos. Justo prompta senserit eos cu, omnesque posidonium liberavisse pri in. Malorum fabulas elaboraret mea in, vel ut harum tacimates posidonium.</p>
      <div class="row">
        <div class="col-md-6">
          <ul class="feat">
            <li>
              <%= image_tag "icons/icon_domestic_3.png", size:"50", data_retina:"true" %>
              <h4>Packing service</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
            <li>
              <%= image_tag "icons/icon_domestic_4.png", size:"50", data_retina:"true" %>
              <h4>Delicate Packing service</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
          </ul>
        </div>
        <div class="col-md-6">
          <ul class="feat">
            <li>
              <%= image_tag "icons/icon_international_3.png", size:"50", data_retina:"true" %>
              <h4>Dedicate Help center</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
            <li>
              <%= image_tag "icons/icon_international_2.png", size:"50", data_retina:"true" %>
              <h4>Transport</h4>
              <p>Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
            </li>
          </ul>
        </div>
      </div><!-- End row -->

      <hr>

      <div class="row">
        <div class="col-md-6">
          <h3>Packing with extra care</h3>
          <p>Ad sed apeirian senserit gloriatur, eu iusto ubique impetus quo. Sea no essent cotidieque reformidans, sea an <strong>persius moderatius</strong> comprehensam, at nam tamquam alterum definiebas. Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
          </div>
        <div class="col-md-6">
          <h3>Insurance</h3>
          <p>Ad sed apeirian senserit gloriatur, eu iusto ubique impetus quo. Sea no <strong>essent cotidieque</strong> reformidans, sea an persius moderatius comprehensam, at nam tamquam alterum definiebas. Nibh facilisi mei eu, essent virtute ius id. Ne ullum consequat sit, dolorum deserunt expetendis no eam.</p>
        </div><!-- End row -->
      </div>
      <hr>
    </div><!-- End col-md-9 -->

    <div class="col-md-3">
      <div class="box_style_1">
        <ul id="cat_nav">
          <li><%= link_to "Moving", services_moving_path %></li>
          <li><%= link_to "Packing and Reassembly", services_packing_and_reassembly_path %></li>
          <li><%= link_to "Storage", services_storage_path %></li>
          <li><%= link_to "Special Furnitures", services_special_furnitures_path %></li>
        </ul>
        <hr>
        <h5>Did you find what you need?</h5>
        <p class="nopadding"><%= link_to "Contact Us", contact_us_path %></p>

      </div><!-- End Box_style_1 -->

      <div class="quote_banner">
        <%= link_to quotation_path do %>
            <i class="icon_calulator"></i> Need a Quotation?
        <%end%>
      </div>

      <div class="box_style_2">
        <h4>Removal tips</h4>
        <h5><i class="icon_toolbox_alt"></i> Preparing</h5>
        <ul>
          <li>Defrost your refrigerator in time for moving day.</li>
          <li>It’s useful to keep a notebook at hand to write down reminders.</li>
          <li>Get in touch with utility companies to verify service start dates at your new home.</li>
        </ul>
        <h5><i class="icon_tag_alt"></i> Packing and labeling</h5>
        <ul>
          <li>Label boxes on all sides so you can see what it contains in a stack without having to move everything around.</li>
          <li>Clearly mark boxes containing fragile goods.</li>
          <li>Pack a suitcase with clothes and toiletries like you’re going on a trip for a few days.</li>
        </ul>
        <p><%= link_to "Read More", tips_path %></p>
      </div>

    </div><!-- End col-md-3 -->

  </div><!-- End row -->
</div><!-- End container -->

app/views/services/storage.html.erb
<section id="sub_header">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8">
        <div class="main_title">
          <h1><i class="icon-home"></i> Storage</h1>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</section><!-- End section -->

<div class="container margin_60">
  <div class="row">
    <div class="col-md-9">
      <%= image_tag "pages/storage/storage-main.jpg", class:"img-responsive border" %>
      <h3>1.200 mq Deposit</h3>
      <p class="add_bottom_30">
        Ad qui consulatu scripserit comprehensam. Eum <strong>purto epicurei cotidieque</strong> at, ius luptatum invidunt no, vim at sint pertinacia repudiandae. Ad cum dicant laboramus delicatissimi, ex has nonumes explicari prodesset, brute tincidunt conclusionemque no has. Sit ullum latine ei. Ius id adhuc iriure torquatos. Justo prompta senserit eos cu, omnesque posidonium liberavisse pri in. Malorum fabulas elaboraret mea in, vel ut harum tacimates posidonium.
      </p>
      <h3>900 mq Deposit</h3>
      <p class="add_bottom_30">
        Ad qui consulatu scripserit comprehensam. Eum <strong>purto epicurei cotidieque</strong> at, ius luptatum invidunt no, vim at sint pertinacia repudiandae. Ad cum dicant laboramus delicatissimi, ex has nonumes explicari prodesset, brute tincidunt conclusionemque no has. Sit ullum latine ei. Ius id adhuc iriure torquatos. Justo prompta senserit eos cu, omnesque posidonium liberavisse pri in. Malorum fabulas elaboraret mea in, vel ut harum tacimates posidonium.
      </p>
      <h3>600 mq Deposit</h3>
      <p class="add_bottom_30">
        Ad qui consulatu scripserit comprehensam. Eum <strong>purto epicurei cotidieque</strong> at, ius luptatum invidunt no, vim at sint pertinacia repudiandae. Ad cum dicant laboramus delicatissimi, ex has nonumes explicari prodesset, brute tincidunt conclusionemque no has. Sit ullum latine ei. Ius id adhuc iriure torquatos. Justo prompta senserit eos cu, omnesque posidonium liberavisse pri in. Malorum fabulas elaboraret mea in, vel ut harum tacimates posidonium.
      </p>
      <h3>300 mq Deposit</h3>
      <p class="add_bottom_30">
        Ad qui consulatu scripserit comprehensam. Eum <strong>purto epicurei cotidieque</strong> at, ius luptatum invidunt no, vim at sint pertinacia repudiandae. Ad cum dicant laboramus delicatissimi, ex has nonumes explicari prodesset, brute tincidunt conclusionemque no has. Sit ullum latine ei. Ius id adhuc iriure torquatos. Justo prompta senserit eos cu, omnesque posidonium liberavisse pri in. Malorum fabulas elaboraret mea in, vel ut harum tacimates posidonium.
      </p>
    </div><!-- End col-md-9 -->

    <div class="col-md-3">
      <div class="box_style_1">
        <ul id="cat_nav">
          <li><%= link_to "Moving", services_moving_path %></li>
          <li><%= link_to "Packing and Reassembly", services_packing_and_reassembly_path %></li>
          <li><%= link_to "Storage", services_storage_path %></li>
          <li><%= link_to "Special Furnitures", services_special_furnitures_path %></li>
        </ul>
        <hr>
        <h5>Did you find what you need?</h5>
        <p class="nopadding"><%= link_to "Contact Us", contact_us_path %></p>

      </div><!-- End Box_style_1 -->

      <div class="quote_banner">
        <%= link_to quotation_path do %>
            <i class="icon_calulator"></i> Need a Quotation?
        <%end%>
      </div>

      <div class="box_style_2">
        <h4>Removal tips</h4>
        <h5><i class="icon_toolbox_alt"></i> Preparing</h5>
        <ul>
          <li>Defrost your refrigerator in time for moving day.</li>
          <li>It’s useful to keep a notebook at hand to write down reminders.</li>
          <li>Get in touch with utility companies to verify service start dates at your new home.</li>
        </ul>
        <h5><i class="icon_tag_alt"></i> Packing and labeling</h5>
        <ul>
          <li>Label boxes on all sides so you can see what it contains in a stack without having to move everything around.</li>
          <li>Clearly mark boxes containing fragile goods.</li>
          <li>Pack a suitcase with clothes and toiletries like you’re going on a trip for a few days.</li>
        </ul>
        <p><%= link_to "Read More", tips_path %></p>
      </div>

    </div><!-- End col-md-3 -->

  </div><!-- End row -->
</div><!-- End container -->